import MainTemplate from "@/components/MainTemplate";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pokemons",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainTemplate>
      {children}
    </MainTemplate>
  );
}
